from __future__ import annotations

import json
import sys
from collections import Counter
from html.parser import HTMLParser
from pathlib import Path


ROOT = Path(__file__).parent / "website"


class PageParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.title = ""
        self.in_title = False
        self.meta: dict[str, str] = {}
        self.canonical = ""
        self.forms = 0
        self.status_regions = 0
        self.empty_links: list[str] = []

    def handle_starttag(self, tag, attrs):
        values = dict(attrs)
        if tag == "title":
            self.in_title = True
        elif tag == "meta":
            key = values.get("name") or values.get("property")
            if key:
                self.meta[key] = values.get("content", "")
        elif tag == "link" and "canonical" in values.get("rel", ""):
            self.canonical = values.get("href", "")
        elif tag == "form":
            self.forms += 1
        elif values.get("role") == "status":
            self.status_regions += 1
        elif tag == "a" and values.get("href") in ("", "#"):
            self.empty_links.append(values.get("href", ""))

    def handle_endtag(self, tag):
        if tag == "title":
            self.in_title = False

    def handle_data(self, data):
        if self.in_title:
            self.title += data


records = []
for path in sorted(ROOT.glob("*.html")):
    parser = PageParser()
    parser.feed(path.read_text(encoding="utf-8"))
    robots = parser.meta.get("robots", "").lower()
    indexable = "noindex" not in robots and path.name != "404.html"
    records.append(
        {
            "file": path.name,
            "title": parser.title.strip(),
            "description": parser.meta.get("description", "").strip(),
            "canonical": parser.canonical,
            "indexable": indexable,
            "og_title": bool(parser.meta.get("og:title")),
            "og_description": bool(parser.meta.get("og:description")),
            "og_type": bool(parser.meta.get("og:type")),
            "forms": parser.forms,
            "status_regions": parser.status_regions,
            "empty_links": parser.empty_links,
        }
    )

errors: list[str] = []
warnings: list[str] = []
indexable = [item for item in records if item["indexable"]]

for field in ("title", "description", "canonical"):
    counts = Counter(item[field] for item in indexable if item[field])
    for value, count in counts.items():
        if count > 1:
            errors.append(f"duplicate {field}: {value} ({count})")

for item in records:
    if item["indexable"] and not item["canonical"]:
        errors.append(f"{item['file']}: missing canonical")
    if item["empty_links"]:
        errors.append(f"{item['file']}: empty or hash-only links")
    if item["forms"] and item["status_regions"] < item["forms"]:
        errors.append(f"{item['file']}: form without status region")
    if item["indexable"] and not all(
        (item["og_title"], item["og_description"], item["og_type"])
    ):
        warnings.append(
            f"{item['file']}: Open Graph must be generated by the production template"
        )

report = {
    "page_count": len(records),
    "indexable_count": len(indexable),
    "error_count": len(errors),
    "warning_count": len(warnings),
    "errors": errors,
    "warnings": warnings,
    "pages": records,
}
(ROOT / "qa" / "advanced-audit.json").write_text(
    json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
)
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
print(json.dumps(report, ensure_ascii=False, indent=2))
